---
 - name: Deploy and start Apache httpd service
   hosts: node-test
   become: true
   vars: 
      web_pkg: httpd
      web_srv: httpd
      rule: http
   tasks: 
       - name: required pkgs are installed & up to date
         yum: 
          name: "{{ web_pkg }}"
          state: latest
       - name: the {{ web_srv }} service is started & enabled
         service:
          name: "{{ web_srv }}"
          enabled: true
          state: started
       - name: web content is in place
         copy: 
            content: "Example web content"
            dest: /var/www/html/index.html
       - name: The firewall port for {{ rule }} is open
         firewalld: 
             service: "{{ rule }}"
             permanent: true
             immediate: true
             state: present
 

